# GENERAL CONFIG
server:
  servlet.context-path: / # Context path of the application.
  port: ${SERVER_PORT:8080} # Server HTTP port.
springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operations-sorter: alpha
    tags-sorter: alpha
amazon.dynamodb.endpoint: http://localhost:8000/
amazon.aws.accesskey: ${AWS_ACCESS_KEY:access-test}
amazon.aws.secretkey: ${AWS_SECRET_KEY:secret-test}
cloud.aws.sqs.orders-queue: ${AWS_SQS_URL:localhost:5003/}
cloud.aws.sqs.orders-dlq: ${AWS_SQS_DLQ_URL:localhost:5003/}
spring:
  profiles:
    active: localhost